let h1=document.getElementById("h1")
console.log(h1)
let h2=document.getElementsByClassName("h2")
console.log(h2)
let hh1=document.getElementsByTagName("h1")
let p1=document.querySelectorAll("#p1")
let p2=document.querySelector("#p1")
console.log("simple p",p2)
console.log("multiple p",p1)
